title: Marissa Jaikaew
description: a Data Analyst with a specialized background in pharmacy, proficient in Python, R, and Tableau. My work reflects a deep commitment to excellence, blending data analysis  to drive operational improvements and innovative insight.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
