title: Marissa Jaikaew
description: Explore the Portfolio of a Junior Data Analyst: Dive into My Professional Journey and Data Projects.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
